/**
 * A certificate in the shape earlier versions of this extension produced:
 * a CA certificate with no subjectAltName and no extended key usage.
 *
 * LocalSend rejects it during the handshake, so it exists here as a fixture
 * for the checks that detect and replace such a certificate. It is a literal
 * sample rather than something generated by the test, so the suite needs no
 * openssl and behaves the same on Windows, Linux and macOS.
 */
export const LEGACY_CA_CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIURdkzIVt/B1rXEKN7ekCFvBPTVjAwDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UEAwwJTG9jYWxTZW5kMB4XDTI2MDkwMjEwMjk1N1oXDTM2MDgz
MDEwMjk1N1owFDESMBAGA1UEAwwJTG9jYWxTZW5kMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA1kdu18sTEOjWMpmqHW5Gt4/3uI4kv9bn43pdIYPCa3Oo
4jRm4tjcI6LVQGU53KNt6KWKul8p/CqEjMcd4g2JpqtNS6G0a3P5nLmhUXvSfAPC
uA7Y8Trxem0P5JcS4/aevQHevSYB532YXXDrZnaqDgW0M31lqTk1fE1gFxGeZG+X
v8KAlyzY3cM2f+bvGPYKJtUec+byZLZLDJJE/Gwi3gQY2iQRSVsKRF11o4e5S7IR
8Uwzrmkba5Fe7SdIaa3whL4bn7i1NpheA2Z2ewhhnSuc/ROQE/E7nYNUYvvzN3EV
2C2hsQhq0oogF21YVtl+q/AN09tLmw9vp5blQL7AHwIDAQABo1MwUTAdBgNVHQ4E
FgQUmaNG/srltCyyVAcZqtd6BZBIRRkwHwYDVR0jBBgwFoAUmaNG/srltCyyVAcZ
qtd6BZBIRRkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAMpGM
g9//WvawkB1qdssUJ9mZ7xckhFA3rjSEeeDkX1DRxDQAkNYXlkzGcXRX+AYrlaNY
2cOF/lOvQx/KoD68mGQuIdN9zhC0BHS9oH9RVkz0vwtvhvsOJp5byerniRC59qrm
PKE385QV43TTpieaG++/gnIv60nkCrlq35IPR6fIXCDglFepwzSWwSNsDkVHetXm
N92Jy/97MLMTKJZftvcKaJB9S9iZaR6LQ2H0ZjvTLd8VQ4eIXNrZekJ7wAQ0+07v
ZNhcgLZHWWQWrFPiEs5aaeQQxKH/qqvlwbxk0pKOPX1ohU2j66ZoUF/nQtXkvb4j
NCUec9tUKG5Moy7wRQ==
-----END CERTIFICATE-----
`;
